# Generated by Django 4.2.2 on 2023-07-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_codesnippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeSnippet',
        ),
    ]
